name: hydrogen
description: A super simple design language
version: 1.0.0
homepage: https://github.com/ArcaneArts/hydrogen
environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1